import Img from "./classes/img";

// Tilemaps
const groundTiles = [
  19, 20, 24, 25, 32, 35, 36, 37, 38, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
  52, 53, 54, 55, 57,
];
const fullTiles = [
  [
    0, 2, 3, 4, 0, 5, 6, 7, 8, 9, 10, 11, 0, 0, 5, 6, 7, 0, 5, 6, 7, 2, 3, 4, 0,
    2, 3, 4, 0, 5, 6, 7, 2, 3, 4, 0, 12, 0, 2, 3, 3, 4, 5, 6, 7, 0, 2, 3, 4, 12,
    0, 0, 5, 6, 7, 2, 3, 3, 4, 0, 0, 0, 13, 0, 0, 14, 2, 3, 4, 8, 9, 10, 11, 12,
    0, 5, 6, 7, 0, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ],
  [
    4, 5, 6, 7, 0, 12, 0, 0, 13, 0, 0, 14, 9, 10, 11, 0, 0, 0, 0, 0, 0, 5, 6, 7,
    0, 5, 6, 7, 0, 12, 0, 0, 5, 6, 7, 12, 0, 0, 5, 6, 6, 7, 0, 0, 12, 0, 5, 6,
    7, 0, 2, 3, 4, 0, 0, 5, 6, 6, 7, 0, 12, 2, 15, 0, 0, 16, 5, 6, 7, 13, 0, 0,
    14, 9, 10, 11, 0, 0, 0, 12, 0, 5, 6, 7, 2, 3, 4, 12, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0,
  ],
  [
    7, 12, 0, 0, 2, 3, 4, 12, 15, 0, 0, 16, 0, 0, 14, 12, 0, 8, 9, 10, 11, 12,
    17, 18, 2, 3, 4, 12, 0, 0, 2, 3, 4, 0, 0, 19, 20, 2, 3, 4, 0, 0, 8, 9, 10,
    11, 0, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 5, 15, 0, 8, 9, 10, 11, 12,
    21, 0, 0, 16, 0, 0, 14, 12, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 12,
  ],
  [
    3, 4, 17, 18, 5, 6, 7, 2, 15, 17, 18, 16, 0, 0, 16, 3, 4, 13, 0, 0, 14, 0,
    22, 23, 5, 6, 7, 2, 3, 4, 5, 6, 7, 0, 2, 24, 25, 5, 6, 7, 0, 0, 13, 26, 0,
    14, 0, 5, 6, 7, 0, 0, 0, 12, 2, 3, 4, 0, 0, 2, 3, 4, 15, 0, 13, 17, 18, 14,
    17, 18, 0, 8, 9, 10, 11, 27, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 2, 3, 4,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 28, 28, 28, 28, 28, 28,
  ],
  [
    6, 7, 22, 23, 0, 0, 0, 5, 21, 22, 23, 9, 10, 11, 16, 6, 7, 21, 0, 0, 27, 29,
    23, 30, 29, 29, 29, 5, 6, 7, 0, 0, 23, 0, 5, 24, 25, 0, 0, 0, 17, 18, 15,
    31, 0, 16, 23, 0, 0, 0, 19, 20, 0, 0, 19, 32, 20, 0, 0, 5, 6, 7, 15, 0, 21,
    23, 33, 27, 22, 23, 0, 34, 0, 0, 14, 19, 32, 32, 32, 35, 0, 0, 0, 0, 2, 3,
    4, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 37, 38, 38, 38, 38, 38, 38,
    38, 38,
  ],
  [
    39, 29, 23, 30, 29, 0, 0, 29, 29, 23, 30, 29, 29, 14, 40, 29, 29, 29, 19,
    32, 32, 32, 32, 32, 32, 19, 20, 39, 29, 29, 29, 0, 30, 18, 29, 24, 25, 39,
    29, 29, 23, 23, 15, 41, 0, 16, 30, 18, 39, 19, 42, 25, 3, 4, 24, 42, 42, 20,
    39, 39, 29, 0, 21, 29, 39, 30, 23, 39, 23, 30, 29, 29, 39, 19, 32, 42, 42,
    43, 44, 45, 0, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 36, 37,
    38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
  ],
  [
    32, 46, 46, 46, 32, 32, 32, 20, 32, 32, 32, 32, 32, 32, 46, 32, 32, 32, 42,
    47, 42, 47, 47, 47, 42, 24, 42, 46, 32, 20, 32, 32, 46, 46, 46, 47, 47, 46,
    46, 46, 46, 32, 46, 46, 46, 46, 46, 46, 46, 42, 42, 25, 6, 7, 24, 42, 42,
    47, 46, 46, 46, 46, 32, 46, 32, 46, 46, 46, 46, 32, 32, 32, 32, 42, 42, 42,
    48, 49, 50, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 51,
    52, 52, 52, 53, 37, 38, 38, 38, 38, 38,
  ],
  [
    54, 55, 55, 55, 54, 47, 54, 25, 47, 54, 47, 42, 47, 54, 55, 54, 47, 54, 54,
    55, 54, 55, 55, 55, 54, 24, 54, 55, 54, 47, 20, 54, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 54, 55, 55, 55, 55, 55, 55, 55, 54, 47, 25, 56, 56, 24, 47, 54,
    55, 55, 55, 55, 55, 54, 55, 54, 55, 55, 55, 55, 54, 42, 47, 47, 54, 47, 48,
    49, 57, 50, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
    56, 56, 56, 56, 51, 52, 52, 52, 52, 51, 52, 52, 52, 52, 52,
  ],
  Array(110).fill(0),
];
export const groundTilemap = fullTiles
  .map((tiles) => tiles.map((tile) => (groundTiles.includes(tile) ? tile : 0)))
  .flat();
export const backgroundTilemap = fullTiles
  .map((tiles) => tiles.map((tile) => (groundTiles.includes(tile) ? 0 : tile)))
  .flat();

// Colors
// https://lospec.com/palette-list/en4
export const palette = [
  "fbf7f3", // primary
  "e5b083", // complementary1
  "426e5d", // complementary2
  "20283d", // accent
];
const [primary, complementary1, , accent] = palette;

// Sprites
export const spriteImg = new Img({
  data: "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@HIIA@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@HIAHIIA@@@@@@@HQ[[JA@@@@HIAHIIA@HI@@@@@HIIA@@@@@HIAHIIA@@@@@HIAHIIA@HI@@@@@HIIA@@@@@HIAHIIA@@@@@@@@HIIA@HI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Y[KQ[[JI@@@@@HY[[[[KA@@@Y[KQ[[JAYSA@@@HQ[[JI@@@@Y[KQ[[JI@@@@Y[KQ[[JAYSA@@@HQ[[JA@@@@Y[KQ[[JA@@@@@@HQ[[JAYSA@HIAHIIA@HI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@HIA@@@@HZ[[[[[[[I@@@@Q[[[[[[J@@HZ[[[[[[KY[A@@HY[[[[[I@@HZ[[[[[[SI@@HZ[[[[[[KY[A@@HY[[[[KA@@HZ[[[[[[KA@@@@HY[[[[KY[A@Y[KQ[[JAYSA@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@HQ[JA@@@H[[[[[[[K[A@@HZ[[[[[[SA@H[[[[[[[[J[A@@Q[[[[[K[A@H[[[[[[[YSA@H[[[[[[[[J[A@@Q[[[[[[J@@H[[[[[[[[J@@@@Q[[[[[[J[AHZ[[[[[[KY[A@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@IQ[[[J@@@H[[[[[[[[YK@@H[[[[[[[[A@H[[[[[[[[SYA@HZ[[[[[[YK@H[[[[[[[K[J@H[[[[[[[[SYA@HZ[[[[[[SA@H[[[[[[[[SA@@HZ[[[[[[SYAH[[[[[[[[J[A@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@H[K[[K[A@@HZ[[[[[[[YSA@Q[[[[[[[[K@HZ[[[[[[[[YA@H[[[[[[[YSAHZ[[[[[[K[SAHZ[[[[[[[[YA@H[[[[[[[[A@HZ[[[[[[[[A@@H[[[[[[[[YAH[[[[[[[[SYA@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Y[S[[[YA@@@Y[[[[[[[[K@@Y[[[[[[KKK@@Y[[[[[[[[K@@Q[[[[[[[[K@@Y[[[[[[[[IA@Y[[[[[[[[K@@Q[[[[[[[[K@@Y[[[[[[[[K@@Q[[[[[[[[K@HZ[[[[[[[[YA@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Y[[[[[YK@@@Q[[[[[[J[A@HZ[[[[[[KKSA@Q[[[[[[KKK@@Y[[[[[[J[A@@Q[[[[[[JKZJ@Q[[[[[[KKK@@Y[[[[[[KKK@@Q[[[[[[KKK@@Y[[[[[[KKK@@Y[[[[[[[[K@@@@@@IIA@@@@@@@@HII@@@@@@@@@@@@@@@@@@@@@HII@@@@@@@@@@HIA@@@@@@@@@HA@@@@@@@@@@@@@@@@@@@@@@II@@@@@@@@@HIIA@@@@@@@@HIIA@@@@@@Y[[[[[[K@@@HZ[[[[[[YA@H[[[[[[[KK[A@HZ[[[[[KKSAHZ[[[[[[[YA@@HZ[[[[[[Q[K@HZ[[[[[KKSAHZ[[[[[[KKSA@HZ[[[[[KKSAHZ[[[[[[KKSA@Q[[[[[[KKK@@@@@IZ[JA@@@@@@HQ[SI@@@@@@@@HIIA@@@@@@@HQ[SI@@@@@@@IHQ[JAA@@@@HA@QJ@@@@@@@@@@@@@@@@@@@@@HZSA@@@@@@@HQ[[JA@@@@@@HQ[[JA@@@@@Y[[[[[[J@@@H[[[[[[[K@@H[[S[[[[[[[A@H[[[[[[KK[AH[[[[[[[[K@@@H[[[[[[[K[K@H[[[[[[KK[AH[[[[[[[KK[A@H[[[[[[KK[AH[[[[[[[KK[A@HZ[[[[[KKSA@@@HZ[[[J@@@@@@Q[[[SA@@@@@@HQ[[J@@@@@@@Q[[[SA@@@@@HRQ[[[JK@@@@QJ@QJ@@@@@@@@@@@@@@@@@@@@@H[[A@@@@@@@Q[[[[J@@@@@@Q[[[[J@@@@@Q[[[[JSA@@@Q[[[[[[[K@@H[[K[[[[Y[[A@Q[[[[[[[[[AH[[S[[[[[K@@@Q[[[[[[[K[K@Q[[[[[[[[[AH[[S[[[[[[[A@Q[[[[[[[[[AH[[S[[[[[[[A@H[[[[[[KK[A@@@Q[[[[K@@@@@@Y[[[[A@@@@@@Q[[[[A@@@@@HI[[[[IA@@@@Q[[[[[KK@@@@QRIII@@@@@@@@@@@@@@@@@@@@@Q[[J@@@@@@HI[[[K[A@@@@HI[[[K[A@@@@HZ[[[[I@@@@Y[[[[[[[K@@H[[K[[[[K[ZA@Y[[[[[[Y[[AH[[K[[[[[K@@@Y[[[[[[[K[K@Y[[[[[[Y[[AH[[K[[[[Y[[A@Y[[[[[[Y[[AH[[K[[[[Y[[A@Q[[[[[[[[[A@@@Y[[[[SA@@@@HZ[[[KK@@@@@HZ[[[[A@@@@@Q[Z[YYJK@@@@Q[[[[[SJ@@@@QJY[SI@@@@@@@@@@@@@@@@@@@@YKKK@@@@@@Q[Z[[[YJ@@@@Q[Z[[[YJ@@@@Y[[[[[K@@@@Y[[[[[[[K@@HZ[Y[[[[KIYA@Y[[[[[[K[ZAH[[K[[[[[K@@@Y[[[[[[[Z[K@Y[[[[[[K[ZAH[[K[[[[K[ZA@Y[[[[[[K[ZAH[[K[[[[K[ZA@Y[[[[[[Y[[A@@H[[[KKSA@@@@H[[[[KK@@@@@H[[[KKK@@@@@Y[[[YYKK@@@@Q[[[[[[I@@@@QQ[[[SA@@@@@@@@@@@@@@@@@@@YKKK@@@@@@Y[[[[[YK@@@@Y[[[[[YK@@@@Y[[[[[K@@@@Y[[[[[[[KA@@YK[[[[[K[SA@Y[[[[[[KIYAHZ[Y[[[[[KA@@Y[[[[[[[[[J@Y[[[[[[KIYAHZ[Y[[[[KIYA@Y[[[[[[KIYAHZ[Y[[[[KIYA@Y[[[[[[K[ZA@@Q[[[KK[K@@@@H[SY[KK@@@@@Y[[[KKKA@@@@Y[[[YYKK@@@@HZ[[KK[A@@@@HZ[[[[A@@@@@@@@@@@@@@@@@@@YKKK@@@@@@Y[[[[[[I@@@@Y[[[[[[I@@@@Y[[[[[K@@@@Y[[[[[[[YK@@IY[[[[[Y[K@@Y[[[[[[K[SA@YK[[[[[[YK@@Y[[[[[[[[[A@Y[[[[[[K[SA@YK[[[[[K[SA@Y[[[[[[K[SA@YK[[[[[K[SA@Y[[[[[[KIYA@@Y[[[KK[K@@@@H[[K[[K@@@@@Y[[[KKKJ@@@@Q[[[[[KJ@@@@HY[[KK[A@@@@H[[[[[J@@@@@@@HIII@@@@@@@@YKKK@@@@@@Q[[[[KKK@@@@Q[[[[[SA@@@@Y[[[[[K@@@@Q[[[[[[J[SA@Q[[[[[[[[K@@Q[[[[[[Y[K@@IY[[[[[J[SA@Q[[[[[[[[SA@Q[[[[[[Y[K@@IY[[[[[Y[K@@Q[[[[[[Y[K@@IY[[[[[Y[K@@Y[[[[[[K[SA@@Y[Z[[[SK@@@@HZ[K[[K@@@@@Y[Z[[[KK@@@@HQ[[[[KA@@@@@Q[[KK[A@@@@Q[[[[[KA@@@@@HQ[[[I@@@@@@@Y[[K@@@@@@HQ[[[[YK@@@@HQ[[[[K@@@@@Q[[[[[K@@@@Q[[[[[[[[K@HJ[[[[[[[[A@@Q[[[[[[[[K@@Q[[[[[[[[K@@Q[[[[[[[[J@@Q[[[[[[[[J@@Q[[[[[[[[J@@Q[[[[[[[[JAHQ[[[[[[[[J@@Q[[[[[[Y[K@@@Q[Z[[[SK@@@@HQ[Y[KK@@@@@Q[Y[[[KK@@@@@Y[[K[J@@@@@@QKY[[SI@@@@Y[[[[[KJ@@@@HY[[[[SA@@@@@@Y[[K@@@@@@@Y[[[[YJ@@@@@Y[[[[K@@@@@H[[[[[KA@@HJ[[[[[[[[A@HJZ[[[[[[SA@HJ[[[[[[[[A@HJ[[[[[[[[A@@H[[[[[[[[A@@H[[[[[[[[A@@H[[[[[[[[A@@H[[[[[[[[QJQJ[[[[[[[[A@HQ[[[[[[[[JA@@HZQ[[YKJ@@@@III[[[J@@@@@HZY[[YKJ@@@@HQ[[[[QA@@@@@QQJ[[KJ@@@@Y[Z[[[KK@@@@Q[[[[[[I@@@@@@Y[YK@@@@@@HQ[[[[[A@@@@HQ[[[[K@@@@@HZ[[[[YJ@@HJZ[[[[[[SA@QRQ[[[[[[J@@HJZ[[[[[[SA@HJZ[[[[[[SA@@HZ[[[[[[SA@@HZ[[[[[[SA@@HZ[[[[[[SA@@HZ[[[[[[SQJQJZ[[[[[[SA@QJ[[[[[[[[QJ@@@IQ[[[JA@@@@QJZ[[SA@@@@@@IQ[[[JA@@@@HJZ[[SQA@@@@@HRJ[YQJ@@@@Q[K[[[KK@@@@Q[[[KK[I@@@@@@Q[YJ@@@@@@HJZ[[[SA@@@@HJZ[[[SA@@@@@Q[[[[[J@@QRQ[[[[[[J@@QRIY[[[[KA@@QRQ[[[[[[J@@QRQ[[[[[[J@@@IQ[[[[[[JI@@IQ[[[[[[JI@@IQ[[[[[[JI@@IQ[[[[[[JRAHRQ[[[[[[JI@QJZ[[[[[[SQJ@@@HIR[SI@@@@@QRQ[[JI@@@@@@HIZ[SA@@@@@HRIZSIRA@@@@@HRRYKRJ@@@@H[[Y[[KK@@@@HZZ[KKSI@@@@@@I[[I@@@@@@HRIZ[SI@@@@@HRIZ[SIA@@@@@IQ[[[SI@@QRIY[[[[KA@@QJRJQ[[JA@@@QRIY[[[[KA@@QRIY[[[[KA@@HRJY[[[[KQRAHRJY[[[[KQRAHRJY[[[[KQRAHRJY[[[[KQJ@@QJY[[[[KQRAHRQ[[[[[[JRA@@@QRIIIRA@@@@QRIIIQRA@@@@@HRIII@@@@@@@QRIIRJ@@@@@@HRRQQRA@@@@HZ[Y[[JA@@@@@IY[[[KA@@@@@@HYKA@@@@@@@QRIII@@@@@@@QRIII@@@@@@@QJIIII@@@QJRJQ[[JA@@@QJRAHIIA@@@@QJRJQ[[JA@@@QJRJQ[[JA@@@QRRJQ[[JQRRJQRRJQ[[JQRRJQRRJQ[[JQRRJQRRJQ[[JQRA@@HRJQ[[JQRRJ@QJY[[[[KQJ@@@HRRJIQRJ@@@@HI@@HRRA@@@@@@QRJJ@@@@@@@HRJ@IA@@@@@@@QJIQJ@@@@@@Q[Q[SA@@@@@HRIZ[YQJ@@@@@@HJQA@@@@@@@HRJRRA@@@@@@HRJRRA@@@@@@HRRRJ@@@@QJRAHIIA@@@@HAI@@@@@@@@@QJRAHIIA@@@@QJRAHIIA@@@@QRRJHIIAQRRJQRRJHIIAQRRJQRRJHIIAQRRJQRRJHIIAII@@@@IIHIIAQRRJ@HRJQ[[JQRA@@@@IIA@IIA@@@@@@@@@II@@@@@@@HIIA@@@@@@@@IA@@@@@@@@@@HI@IA@@@@@@HIAIA@@@@@@@IIIIIIA@@@@@@@II@@@@@@@@@IAIIA@@@@@@@IAIIA@@@@@@@IIIA@@@@HAI@@@@@@@@@@@@@@@@@@@@@HAI@@@@@@@@@HAI@@@@@@@@@HIIA@@@@HIIAHIIA@@@@HIIAHIIA@@@@HIIAHIIA@@@@@@@@@@@@@@@@HIIA@@IIHIIAII@@",
  width: 504,
  height: 25,
  shouldFlip: true,
  colors: [accent, complementary1, primary].join(""),
});

export const tilesetImg = new Img({
  data: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZIIIIIIIIIIIIIIQKIIIIIIIIIIIIIIIIIZ[[IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZ[SIIIIIIIIIIIIIQ[SIIIIIIIIIIIIIIIZ[SRRIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZSRJIIIIIIIIIIIIIIQ[IIIIIIIIIIIIIQ[SRRRRIIIIIIIIIIIIIIIIIQ[[[[JIIIIIIIIISIIIIIIIIIIIIIIIIIQZIIIIIIIIIIIIZ[RRRJIIIIIIIIIIIIIIIIIII[RRRR[IIIIIIIIIZSJIIIIIIIIIIIIIIIIZIIIIIIIIIIIYSRRJIIIIIIIIIIIIIIIIIIIIYRJIIQRKIIIIIIIIIZSIIIIIIIIIIIIIIIQZIIIIIIIIIIQSRRIIIIIIIIIIIIIIIIIIIIIISJIIIIQZIIIIIIIIIIZJIIIIIIIIIIIIIIQZIIIIIIIIII[RRIIIIIIIIIIIIIIIIIIIIIIISIIIIIIZIIIIIIIIIIQ[IIIIIIIIIIIIIIRSIIIIIIIIIYRRIIIIIIIIIIIIIIIIIIIIIIZ[IIIIIIII[SIIIIIIIIIISJIIJIIIIIIQIQRKIIIIIIIIISRIIIIIIIIIIIIIIIIIIIIIIYSRIIIIIIIIRZKIIIIIIIIIZRRRRIIIIIIRRRZKIIIIIIIIYRJIIIIIIIIIIIIIIIIIIIIIISRIIIIIIIIIIRZIIIIIIIIIQ[RRRJIIIIQRRZ[IIIIIIIIISRIIIIIIIIIIIIIIIIIIIIIIYRIIIIIIIIIIIIZJIIIIIIIIIZ[[RRJIIQRZZ[KIIIIIIIIYRJIIIIIIIIIIIIIIIIIIIIIIZJIIIIIIIIIIIIQKIIIIIIIIIIZ[[RRRRRR[[JIIIIIIIIISRIIIIIIIIIIIIIIIIIIIIIIISJIIIIIIIIIIIIQKIIIIIIIIIIIIZSRRRR[SIIIIIIIIIIYRJIIIIIIIIIIIIIIIIIIIIIIISIIIIIIIIIIIIIQKIIIIIIIIIIIIQ[[[[[[JIIIIIIIIIIZRIIIIIIIIIIIIIIIIIIIIIIIISIIIIIIIIIIIIIQKIIIIIIIIIIIIIQ[[[[JIIIIIIIIIIISRIIIIIIIIIIII[[SIIIIIIIIIIIIIIRRRRRRIIYRJIIIIIIIIRRKISJIIIIIIIIIIQQRZIIIIIIZ[[SIIIIIIRRZ[SIIIIIIIIIIIQIJIJQIJIZRIIIIIIIIIRRSISJIIIIIIIIIIJRRZIIIIIZJIIQSIIIIIRRRRZ[JIIIIIIIIIJIIIIIIQISRIIIIIIIIIQRZISJIIIIIIIIIIQQRZIIIIQKIIIIYJIIIIIIQRRR[SIIIIIIIIJIIIIIIQQSJIIIIIIIIIRRZJSJIIIIIIIIIIJRRZIIIIYIQ[[JIKIIIIIIIIQRRZKIIIIIIIJIQIIQIQQSJIIIIIIIIIQRZJSJIIIIIIIIIIQQRZIIIIRI[RR[IRIIIIIIIIIIRRZJIIIIIIKIRJIRJZYRIIIIIIIIIIJRRKSJIIIIIIIIIIJRRZIIIIKQSIIYJZIIIIIIIIIIIRR[IIIIIIZRZRRZRSYRIIIIIIIIIIQRRKSJIIIIIIIIIIQQRZIIIIKYJIIQKZIIIIIIIIIIIIRRKIIIIIQ[[[[[[JZRIIIIIIIIIIJRRSSJIIIIIIIIIIJRRZIIIIKZJIIIKZIIIIIIIIIIIIIRZIIIIIIIIIIIIISJIIIIIIIIIIQQRZSJIIIIIIIIIIQQRZIIIIKZJIIIKZIIIIIIIIIIIIIQRKIIIIIIIIIIIISJIIIIIIIIIIJRRZSJIIIIIIIIIIJRRZIIIIKZJIIIKZIIIIIIIIIIIIIIRZIIIIIIIIIIIISJIIIIIIIIIIQQRZSJIIIIIIIIIIQQRZIIIIKZJIIIKZIIIIIIIIIIIIIIQRKIIIIIIIIIIISJIIIIIIIIIIJRRZSJIIIIIIIIIIJRRZIIIIKZJIIIKZIIIIIIIIIIIIIIIRZIIIIIIIIIIISJIIIIIIIIIIQQRZSJIIIIIIIIIIQQRZIIIIKZJIIIKZIIIIIIIIIIIIIIIRRKIIIIIIIIIISJIIIIIIIIIIJRRZSJIIIIIIIIIIJRRZIIIIKZJIIIKZIIIIIIIIIIIIIIIQRSIIIIIIIIIISJIIIIIIIIIIQQRZSJIIIIIIIIIIQQRZIIIIKZJIIIKZIIIIIIIIIIIIIIIQRZIIIIIIIIIISJIIIIIIIIIIJRRZSJIIIIIIIIIIJRRZIIIIKZJIIIKZIIIIYddddddddddddddKSJIIIIIIIIIIKZJIIIZ[[SII\\JRRRJRRRJRRRJRcIIIIIIIIIIIIQQRZc[[[[[[[[[[[[[[\\SJIIIIIIIIIIKZJIIZJIIQSI\\RJRRRJRRRJRRRRcIIIIIIIIIIIIJRRZ\\RRRRRRRRRRRRRRcSJIIIIIIIIIIKZJIQKIIIIYJ\\RRRJRRRJRRRJRRcIIIIIIIIIIIIQQRZ\\RIIIIIIIIIIIIRcSJIIIIIIIIIIKZJIYIQ[[JIK\\RRJRRRJRRRJRRRcRRRZIIIIIIIIJRRZTQIIIIIIIIIIIIJbSJIIIIIIIIIIKZJIRI[RR[IR\\RRRRQRRRQRRRQRcKIIaIIIIIIIIQQRZ\\JJJJJJJJJJJJJJcSJIIIIIIIIIIKZJIKQSIIYJZ\\RQRRRQRRRQRRRQcKIIaIIIIIIIIJRRZ\\RRRRRRRRRRRRRRcSJIIIIIIIIIIKZJIKYJIIQKZ\\RRRQRRRQRRRQRRccLadIIIIIIIIQQRZ\\RRRRRRRRRRRRRRcSJIIIIIIIIIIKZJIKZJIIIKZ\\RRQRRRQRRRQRRRcIKaIIIIIIIIIJRRZ\\JRRRJRRRJRRRJRcRJIIIIIIIIIIKZJIKZJIIIKZ\\JRRRJRRRJRRRJRcIKaQRKRZIIIIQQRR\\RJRRRJRRRJRRRRcRJIIIIIIIIIIKZJIKZJIIIKZ\\RJRRRJRRRJRRRRcIKaYIbJaIIIIJRRR\\RRRJRRRJRRRJRRcRJIIIIIIIIIIKZJIKZJIIIKZ\\RRRJRRRJRRRJRRcIKaYIQLaIIIIQQRR\\RRJRRRJRRRJRRRcQJIIIIIIIIIIKZJIKZJIIIKZ\\RRJRRRJRRRJRRRcIKaYIIJaIIIIJJRR\\RRRRQRRRQRRRQRcJJIIIIIIIIIIKZJIKZJIIIKZ\\RRRRQRRRQRRRQRcRKa\\IJIaIIIIQQQQ\\RQRRRQRRRQRRRQcQIIIIIIIIIIIKZJIKZJIIIKZ\\RQRRRQRRRQRRRQcKIIYITIaIIIIIIJJ\\RRRQRRRQRRRQRRcJJIIIIIIIIIIKZJIKZJIIIKZ\\RRRQRRRQRRRQRRcKIIYIdJaIIIIIQQQ\\RRQRRRQRRRQRRRcQIIIIIIIIIIIKZJIKZJIIIKZ\\RRQRRRQRRRQRRRccdd\\dLddIIIIIIIIIRJIRJRJIIIIIIIIKZJIIIKZIIIIIIIIddddddddIIKZIIIIIYRJIIIIdddddddKIIIIY[[[YRRQRRRRIIIIIIIIKZJIIIKZIIIIIIII[[[[[[[[IIKZIIIIIZRIIIII[[[[[[[\\IIIISIIISQRRRRRRIIIIIIIIKZJIIIKZIIIIIIIIRRRRRRRRIIKZIIIIISRIIIIIRRRRRRRcIIIISRRRJQQQRQQRIIIIIIIIKZJIIIKZIIIIIIIIIIIIIIIIIIKZIIIIQSJIIIIIIIIIIIRcIIIISRRRJRJJJJJRIIIIIIIIKZJIIIKZIIIIIIIIIIIIIIIIIIKZIIIIQSJIIIIIIIIIIIJbIIIISZRRSRRRRRRRIIIIIIIIKZJIIIKZIIIIIIIIJJJJJJJJIIKZIIIIYRIIIIIIJJJJJJJcIIII[[SZ[RRRRRRRIIIIIIIIKZJIIIKZIIIIIIIIRRRRRRRRIIKZIIIIYRIIIIIIRRRRRRRcIIII[[[[SRRRRRRRIIIIIIIIKZJIIIKZIIIIIIIIRRRRRRRRIIKZIIIIZRIIIIIIRRRRRRRcIIIIZS[SRRRRRRRRIIIIIJIJKZJIIIKZIQcdd\\JIRJRRRJRRIIKZIIIIRJIIIIIIRJRRRJR[IIIIIIIISRRRSRRRIIQIRIRIKZJIIIKZIcdddd\\IRRJRRRJRIIKZIIIIRJIIIIIIRRJRJRZLIIIIIIII[RSZ[RSZIQJQZQZIKZJIIIKZYddddddKJRRRJRRRIIKZIIIIRJIIIIIIJRRRRR[KIIIIIIIIZ[[SZ[[SIRKRJRKIKZJIIIKZbddddddTRRRJRRRJIIKZIIIIQJIIIIIIRRRJSZcIIIIIIIIIQKZQQKZQQZRRSSKQKZJIIIKZcdddddd\\RQRRRQRRIIKZIIIIJJIIIIIIRQRR[[LIIIIIIIIIIKZQIKZQQSRRSZJZKZJIIIKZddddddddRRQRRRQRIIKZIIIIQIIIIIIIRRQR\\cIIIIIIIIIIIKZQIKZQR[[ZZZQSKZJIIIKZddddddddQRRRQRRRIIKZIIIIJJIIIIIIQRRR\\LIIIIIIIIIIRKZRRKZRZJQSSZRSKZJIIIKZddddddddRRRQRRRQIIKZIIIIQIIIIIIIRRRQdIIIIIIIIIII[[[[[[[[[[[[[[[[IIIIIJIJIIIIQQRRddddddddRJRRRJRRRJRRRJRRRJRRRJRRRJR[IIIIIIIIIIIIIIIIIIIIIIQIRIRIIIIIJRRRddddddddRRJRRRJRRRJRJRJRJRJRJRJRJRZLIIIIRRRRRRRRRRRRRRRRIQJQZQZIIIIIQQRRddddddddJRRRJRRRJRRRRRRZRRRZRRRZRR[KIIIIRRRRRRRRRRRRRRRRIRKRJRKIIIIIJJRRddddddddRRRJRRRJRRRJSRRcSRRcSRRcSZcIIIIIRZRRRZRRRZRRRZRRQZRRSSKQIIIIQQQQddddddddRQRRRQRRRQRR[RZc[RZc[RZc[[LIIIIIR[SZR[SZR[SZR[SZQSRRSZJZIIIIIIJJddddddddRRQRRRQRRRQR\\[[\\\\[[\\\\[[\\\\cIIIIII[[[[[[[[[[[[[[[[R[[ZZZQSIIIIIQQQddddddddQRRRQRRRQRRRd[c\\d[c\\d[c\\\\LIIIIII[S[[[S[[[S[[[S[[ZJQSSZRSIIIIIIIIddddddddRRRQRRRQRRRQcddScddScddSdIIIIIII[RIJQQIJQQIJQQIJK[R[[[ZJIIIIIJIJddddddddRJRRRJRRRJRR[[KIKIIYR[ZdIIIIIIIISRIJJQRJJQRJJQRJZIZSSQ[RIIQIRIRIddddddddRRJRRRJRJRJRKYIIKIIYZQ[\\IIIIIIII[RRQJQIRJQIRJQIRKQ[SZJYRIQJQZQZIddddddddJRRRJRRRRRRZIYIQKIIYZS[dIIIIIIIISRIJIQIJIQIJIQIJ[[R[IQQSIRKRJRKIddddddddRRRJRRRJSRRcIQKRKIIZKYZcIIIIIIII[RRIIQRIIQRIIQRISZR[JQKSQZRRSSKQddddddddRQRRRQRR[RZcIIS[KIIZJQScIIIIIIIISRQQJQQQJQQQJQQQSZZZSJYSQSRRSZJZddddddddRRQRRRQR\\[[\\II[JZIQKJQScIIIIIIII[RIJJQIJJQIJJQIJRSZRZ[[RR[[ZZZQSddddddddQRRRQRRRd[c\\IISIQSRKSYScIIIIIIIISJIJQJIJQJIJQJIJRRRRRRRRZJQSSZRSddddddddRRRQRRRQcddSIQKII[[IZZZcIIIIIIIIddddddddRJRRRJRRRJRRRJRRdd[SIQKIQKYIR[Zd[RIJQQIJQQIJQQIJQQIJY[[[RJR[RJRR[[[[[[[[RRJRRRJRRRJRJRJRd[[RQRKIYIYJZQ[\\SRIJJQRJJQRJJQRJJQRJSIIIRRZ[RRJRRRRRRRRRJRRRJRRRJRRRRRRZ\\RRSZ[SIZIQKZS[d[RRQJQIRJQIRJQIRJQIRSRRRJRK[JRRRIIIIIIIIRRRJRRRJRRRJSRRc\\RRSKIZIKIISKYZcSRIJIQIJIQIJIQIJIQIJSRRRRZQSRSRJIIIIIIIIRQRRRQRRRQRR[RZcSJQ[IIYRKII[JQSc[RRIIQRIIQRIIQRIIQRISZRRRKRSZSRRJJJJJJJJRRQRRRQRRRQR\\[[\\SIIZIIY[KIIZJQScSRQQJQQQJQQQJQQQJQQQ[[SZRKRSKS[SRRRRRRRRQRRRQRRRQRRRd[c\\KIIYIIZIKIIYSYSc[RIJJQIJJQIJJQIJJQIJ[[[[ZQR[Q[ZRRRRRRRRRRRRQRRRQRRRQcddSKIIYSRZIKIIYZZZcSJIJQJIJQJIJQJIJQJIJZS[SZQZKRSZQRJR[RJRRRJR[RJRRRJRR\\d[RKIIY[[KIKIIYR[Zd[RIJQQIJQQIJQQIJQQIJQQIJR[[RRSZSRRZ[RRJRRRZ[RRJRJRJRd\\SRKIIYKYIIKIIYZQ[\\SRIJJQRJJQRJJQRJJQRJJQRJZJQSZR[ZJRK[JRRRJRK[JRRRRRRZd\\RIKIIYIYIQKIIYZS[d[RRQJQIRJQIRJQIRJQIRJQIRSIIZSZRKRZQSRSRJRZQSRSRJSRRc\\[KQKIIZIQKRKIIZKYZcSRIJIQIJIQIJIQIJIQIJIQIJKIIYSZZJRKRSZSRRRKRSZSRR[RZc[SS[KIIZIIS[KIIZJQSc[RRIIQRIIQRIIQRIIQRIIQRIKIIYR[ZIRKRSKS[SRKRSKS[S\\[[\\SR[JZIQKII[JZIQKJQScSRQQJQQQJQQQJQQQJQQQJQQQSIIZZRSQZQR[Q[ZRZQR[Q[ZRd[c\\RRSIQSRKIISIQSRKSYSc[RIJJQIJJQIJJQIJJQIJJQIJZJQS[[KZZQZKRSZQZQZKRSZQcddSRRKII[[IIQKII[[IZZZcSJIJQJIJQJIJQJIJQJIJQJIJR[[RJIZZR[[RRSZSIIIIIIIIQKYIIQKI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ZJQSZR[ZIIIIIIIIYIYJQRKI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@SIIZSZRKIIIIIIIIZIQKZ[SI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@KIIYSZZJIIIIIIIIKIISKIZI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@KIIYR[ZIIIIIIIIIKII[IIYR@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@SIIZZRSQIIIIIIIIKIIZIIY[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ZJQS[[KZIIIIIIIIKIIYIIZI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@R[[RJIZZIIIIIIIIKIIYSRZI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@KR[Z[IQSIIIIIIIIKIIY[[KI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@[[QSIRISIIIIIIIIKIIYKYII@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@SZQSIIKZIIIIIIIIKIIYIYIQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@SZQZIIYZIIIIIIIIKIIZIQKR@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@RKRZKIYZQQQQQQQQKIIZIIS[@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@RKRZYJQ[JJJJJJJJZIQKII[J@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ZQRKZ[[SRRRRRRRRQSRKIISI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ZQRKZSRSRRRRRRRRI[[IIQKI@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  width: 144,
  height: 112,
  shouldFlip: false,
  colors: palette.join(""),
});
